name: Buck Module Test Type Validation
on:
  pull_request:
    path:
      - '**/BUCK'
    branches:
      - 'master'
jobs:
  validate-new-buck-module:
    name: Validate new BUCK file
    runs-on: ubuntu-latest
    steps:
      - name: Check out branch
        uses: actions/checkout@v3

      - name: Get changed files
        id: get_changed_files
        uses: Ana06/get-changed-files@v2.1.0

      - name: Validate new buck file
        run: |
          changed_files=(${{ steps.get_changed_files.outputs.added }})
          echo "Validating ${changed_files[@]}"
          
          for changed_file in "${changed_files[@]}"; do
            if [[ "${changed_file}" == *"BUCK" ]]; then
              if grep -q "java_test_internal" "${changed_file}" && grep -q "test_type='junit'" "${changed_file}"; then
                  echo "${changed_file} is valid."
              else
                  echo "Set ${changed_file}'s java_test_internal.test_type='junit' fix this build failure."
                  exit 1
              fi          
            else
             echo "Skipped validating ${changed_file}."         
            fi          
          done