name: Buck Module Test Type Validation
on:
  pull_request:
    path:
      - '**/BUCK'
    branches:
      - 'master'
jobs:
  validate-new-buck-module:
    name: Validate new BUCK file
    runs-on: ubuntu-latest
    steps:
      - name: Check out branch
        uses: actions/checkout@v3
      - name: Validate new buck file
        run: |
          git fetch origin master
          git diff --name-status origin/master ${{ github.event.pull_request.head.sha }} | grep '^A' | grep BUCK | awk '{print $2}' > buck_files.txt
          echo "$(cat buck_files.txt)"
